### ISSUE TITLE
Save button fade out

### ISSUE THREAD

**Issue by ecwalsh** [ecwalsh/lucidity#3]
Currently adding/removing classes to the save button. 

It fades in correctly but disappears as soon as the input field is empty. Would like to change it to a slow fade-out.

**Comment by horak** [comment]
do we even need a save button? Why not save as you type?

**Comment by ecwalsh** [comment]
Not sure how that would work. Does it save one final time when they exit the window?

**Comment by horak** [comment]
It just saves on every `keyup` event
